name: conversion
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.11
  - pip
  - numpy==2.1.3
  - pyarrow==21.0.0
  - anndata==0.9.2
  - dask==2024.11.2
  - scanpy==1.10.4
  - statsmodels==0.14.6
  - pip:
      - cython
      - aicsimageio==3.3.1
      - pint
      - spatialdata==0.4.0
      - spatialdata-io==0.2.0
      - tifffile
      - git+https://github.com/andrewhill157/barcodeutils
      - git+https://github.com/hubmapconsortium/fastq-utils@v0.2.5