name: conversion
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.11
  - pip
  - numpy==2.1.3
  - pyarrow==21.0.0
  - anndata==0.9.2
  - aicsimageio==3.3.1
  - dask==2024.2
  - pip:
      - pint
      - scanpy==1.10.4
      - scipy>=1.13.0, <2
      - spatialdata==0.4.0
      - spatialdata-io==0.2.0
      - statsmodels==0.14.6
      - tifffile
      - git+https://github.com/andrewhill157/barcodeutils
      - git+https://github.com/hubmapconsortium/fastq-utils@v0.2.5